version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/db-store:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - internal

  backend:
    container_name: backend
    build: 
      context: ./backend
    environment:
      - PYTHONUNBUFFERED=1
    ports: 
      - 3000:3000
    depends_on: 
      - mongodb
    networks:
      - internal

networks:
  internal:
    name: internal