version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: impression-solutions
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/db-store:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo: